<!DOCTYPE html>
<html>

<Head>
    <title> Topics - 3D Models</title>
    <link rel="stylesheet" type="text/css" href="../style.css" />

    <div id="header">
            
        <h1>『EP1000 DIGI FABLAB』</h1>

        <nav>
          <ul class="navlink">
              <li><a href="../index.html" >|Home|</a></li>
              <li><a href="topics.html" >|Topics|</a></li>
              <li><a href="../prj/project.html" >|Projects|</a></li>
            </ul>
      </nav>

    </div>

</Head>



<body>

    <div id="container">

       

        <div id="main" >

            <h2><u>3D Models</u></h2>

            <p>Wow everything seems so real...</p>
            <img width=500px height=auto src="../img/models.PNG" >
           
            
            
           
            

        </div>

        <div id="contents" >

          <h3 id="-u-creating-models-with-fusion-360-u-"><u> Creating models with FUSION 360 </U></h3>
            <p>Following up with previous topic on CAD, FUSION 360 can be used to turn sketches into models. There are 3 ways to do so:</p>
            <ul>
            <li><strong>Extrusion</strong><br>
            -creating a 2D outline in one plane and then extruding or extending the outline of the object in the axis perpendicular to that plane.<br></li>
            <li><strong>Revolution</strong><br>
            -creating a 2D outline in one plane/shape and then revolving the outline/shape a number of degrees in the perpendicular plane. This method is ideal for creating cylindrical objects.<br></li>
            <li><strong>Sculpting</strong><br>
            -This method is akin to playing with plasticine. We start with a defined object e.g. block, cylinder, sphere and then by pushing and pulling surfaces we are able to create a 3D model of the object.<br></li>
            </ul>
            <p>In this page I document several models I made with FUSION 360.</p>
            <ul>
              <li><a href="#nametag" >Nametag</a></li>
              <li><a href="#spinner" >Fidget Spinner</a></li>
              <li><a href="#chess" >Knight Chess piece</a></li>
              <li><a href="#laptop" >Laptop stand</a></li>
              <li><a href="#laserbox" >Laser cut box</a></li>
            </ul>
           
            <div id="nametag">
              <h3 id="nametag-br-">Nametag<br></h3>
              <p>Specifications:</p>
              <ul>
              <li>The nametag should not exceed 30mm X 70mm.</li>
              <li>The key ring hole must have a diameter of at least 2.5 mm with neck width of at least 3.5 mm for strength<br></li>
              <li>Do not make the keytag thicker than 4 mm</li>
              </ul>
              <p><img width=500px height=auto class="center" src="../img/nametag1.jpg" ></p>
              <p>I first start by drawing the nametag with the sketch function.</p>
              <p><img width=500px height=auto class="center" src="../img/nametag (1).png" ></p>
              <p>I created the sketch on the X-Y plane as I want it to be lying flat.</p>
              <p>After that I start the extrusion. I first extrude the center piece by 2mm.</p>
              <p><img width=500px height=auto class="center" src="../img/nametag (2).png" ></p>
              <p>I next extrude the outer shell and the ring by 4mm.<br>
              (You can also extrude the whole body then use shell instead of extruding 2 separate areas: all you need to do is select the area and the thickness of the sides.)</p>
              <p><img width=500px height=auto class="center" src="../img/nametag (3).png" ></p>
              <p>Lastly I extrude the text.<br>
              Extrude function allows you to either join objects or cut the object. Here I extruded the text by 3mm joined.</p>
              <p><img width=500px height=auto class="center" src="../img/nametag (4).png" ></p>
              <p>I then use fillet to round the edges of the ring hole and the body to remove sharp edges.</p>
              <p><img width=500px height=auto class="center" src="../img/nametag (5).png" ></p>
              <p>And heres the final model:</p>
              <iframe src="https://ichat1316.autodesk360.com/shares/public/SH919a0QTf3c32634dcf1bf4af047cdf24a5?mode=embed" width="640" height="480"  class="center" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"  frameborder="0"></iframe>
              <a href="../Fusion 360/nametag v1.f3d" class="center">download</a>
            </div>
              
            <div id="spinner" >

              <h3 id="fidget-spinner-br-">Fidget Spinner<br></h3>
<p>Specifications:</p>
<ul>
<li>An ABEC 608 Bearing of dimensions 8 x 22 x 7 mm for the rotation device and M8 Stainless Steel hex nuts as counter-weights will be used.<br></li>
<li>The radius of your fidget spinner should not exceed 50mm.<br></li>
<li>Maximum thickness of your fidget spinner 8 mm to accommodate the bearing and the M8 nuts.</li>
</ul>
<p>My spinner design will be based on a Biohazard symbol.</p>
<p><img width=200px height=auto class="center" src="../img/hazard.png" ></p>
<p>First I used construction line to mark out the max diameter of the spinner (100mm).</p>
<p><img width=600px height=auto class="center" src="../img/spinner (1).png" ></p>
<p>In the center I draw a circle with the diameter 22mm of the bearing and create another circle with an offset or 2mm.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (2).png" ></p>
<p>I draw one part of the main design.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (3).png" ></p>
<p>Using circular pattern I copy the design part and paste it around the origin point. This saves time from drawing 3 of the same part.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (4).png" ></p>
<p>Now extrusion: I extrude the center ring by 8mm in symmetric so the main desing will be at the center.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (5).png" ></p>
<p>I then extrude the main design by 4mm in symmetric.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (6).png" ></p>
<p>Next is to add the hex weights: I draw a construction line to one corner and draw a hexagon with circumscribe distance with 6.5mm. Then an outer hexagon offest to 2mm.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (7).png" ></p>
<p>Using circular pattern to repeat 2 more hexagons on each corners.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (8).png" ></p>
<p>I first join extrude the outer area on two sides: 2mm on top and 6mm below.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (9).png" ></p>
<p>I then cut extrude the inner hexagon to create a hole for the nuts to fit.</p>
<p><img width=600px height=auto class="center" src="../img/spinner (10).png" ></p>
<p>And the final design:</p>
<iframe src="https://ichat1316.autodesk360.com/shares/public/SH919a0QTf3c32634dcfdd324cb029e9ec9a?mode=embed" width="640" height="480" class="center" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"  frameborder="0"></iframe>
<a href="../Fusion 360/fidget spinner.f3d" class="center">download</a>

<div id="chess" class="center">
  <h3 id="fidget-spinner-br-">Knight Chess piece<br></h3>
  <img width=200px height=auto class="center" src="../img/knight.png" >
  <p>For the chess piece I will be drawing the sketch on the YZ plane.</p>
<p><img width=600px height=auto class="center" src="../img/chess (1).png" ></p>
<p>I create a box as the border for the chess piece.</p>
<p><img width=600px height=auto class="center" src="../img/chess (2).png" ></p>
<p>I inserted a knight image to trace over.</p>
<p><img width=600px height=auto class="center" src="../img/chess (3).png" ></p>
<p> For the base I drew a vertical line at the center of the image and drew half of the base.</p>
<p><img width=600px height=auto class="center" src="../img/chess (4).png" ></p>
<p>Hiding the canvas you can see the final sketch.</p>
<p><img width=600px height=auto class="center" src="../img/chess (5).png" ></p>
<p>Starting with the base, I used Revolve. Select the base sketch and then select the point of rotation.</p>
<p><img width=600px height=auto class="center" src="../img/chess (6).png" ></p>
<p>I then use shell to hollow the base to minimise material usage, setting the thickness to 4mm.</p>
<img width=600px height=auto class="center" src="../img/chess (7).png" >
<p>Then I extrude the knight by 4mm, and the back part by 3mm, extruding symmetrically. </p>
<img width=550px height=auto class="row" src="../img/chess (8).png" ><img width=550px height=auto class="row" src="../img/chess (9).png" >
<p>And the final piece:</p>
<iframe src="https://ichat1316.autodesk360.com/shares/public/SH919a0QTf3c32634dcf57bb6cd6eb41d751?mode=embed" width="640" height="480" allowfullscreen="true" webkitallowfullscreen="true" class="center" mozallowfullscreen="true"  frameborder="0"></iframe>
<a href="../Fusion 360/chess.f3d" >download</a>

<div id="laptop" class="center">
  <h3 id="fidget-spinner-br-">Laptop Stand<br></h3>
  <p>Starting with the leg, I first draw a rough outline of it on the YZ plane.<br>
    <img width=600px height=auto class="center" src="../img/laptopstand (2).png" ><br></p>
    <p>I constraint the slanted angles to be parallel, then set dimensions to fully constraint the sketch.<br>
      <img width=600px height=auto class="center" src="../img/laptopstand (3).png" ><img width=600px height=auto class="center" src="../img/laptopstand (4).png" ><br></p>
    <p>Next I set parameters for thickness and leg-width which can be found under the Modify tab. This makes it easier to adjust material thickness and width without having to redefine every body part.
    <br><img width=600px height=auto class="center" src="../img/laptopstand (5).png" >
    <br>
    To use the parameters, type the parameter name in the object dimension. As you change the parameter value the body dimensions will update and change.
    <br><img width=600px height=auto class="center" src="../img/laptopstand (6).png" >
    <br></p>
    <p>I fillet the edges of the leg, then copied the body a legwidth distance away.
    <br>
    <img width=600px height=auto class="center" src="../img/laptopstand (8).png" >
    <br>
    Next I created a new component &quot;Top&quot;.
    I project the slanted side of the legs to make it more visible. I then create a sketch on the side and draw a rectangle.<br>
    <img width=600px height=auto class="center" src="../img/laptopstand (9).png" >
    <br>
    I then add dimensions to constraint the sketch.<br>
    <img width=600px height=auto class="center" src="../img/laptopstand (11).png" >
    <br>
    I want to add tabs so I can fit the parts together, so I draw a small rectangle at one corner, above the leg piece and added dimensions.<br>
    <img width=600px height=auto class="center" src="../img/laptopstand (12).png" ><br><img width=600px height=auto class="center" src="../img/laptopstand (13).png" >
    <br>
    To add tabs to the other corners, I draw a center line on horizontally and vertically. Then I use the mirror tool to project the rectangle to each corners.
    <br>
    <img width=600px height=auto class="center" src="../img/laptopstand (14).png" ><img width=600px height=auto class="center" src="../img/laptopstand (15).png" ><br></p>
    <p>I extrude the top by negative &quot;thickness&quot;, so the part will cut into the legs, creating it as a new body.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (16).png" ><br></p>
      <p>To cut the tabs, I use the combine tool.
      First selecting the legs as the Target body and the top as the Tool body. I use the cut operation while selecting keep tools.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (18).png" ><br></p>
      <p>The end result is tabs appearing on the legs.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (19).png" ><br></p>
      <p>Next I want to create extra supports for the legs. First I offest a plane so the supports can be drawn in between the legs.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (20).png" ><br>
      <br><img width=600px height=auto class="center" src="../img/laptopstand (21).png" ><br></p>
      <p>I sketch a rectangle support on the offest plane and constraint it.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (22).png" ><br></p>
      <p>As I want to be able to slot the support in, when extruding I leave a gap at where the legs are.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (23).png" ><br></p>
      <p>I then create a midplane to mirror the support to the other side. Similar to before, I use the combine tool to create the slot, with the legs as the Target body and the support as the Tool body, using cut while keeping the tool.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (24).png" ><img width=600px height=auto class="center" src="../img/laptopstand (25).png" ><br></p>
      <p>To make it easier to slot in the tabs, I fillet the tabs and slot edges.
      <br><img width=600px height=auto class="center" src="../img/laptopstand (26).png" ><br></p>
      <p>To add texture, I used Appearance under Modify tab. Simple find for a texture of your choice and drag it onto the part. Here I give the stand an oak wood texture.</p>
      <br><img width=600px height=auto class="center" src="../img/laptopstand.png" ><br>
      <p>Here&#39;s the completed stand:</p>
      <iframe src="https://ichat1316.autodesk360.com/shares/public/SH919a0QTf3c32634dcfc49451b4f0ceb21f?mode=embed" width="640" height="480" allowfullscreen="true" webkitallowfullscreen="true" class="center" mozallowfullscreen="true"  frameborder="0"></iframe>
      <a href="../Fusion 360/laptop stand/laptop stand v4.f3d" class="center">download</a>


</div>

<div id="laserbox" class="center">
  <h3 id="fidget-spinner-br-">Laser cut box<br></h3>

  <p>I first start by making parameters. This will make it easier to modify and adjust dimensions without the need of redrawing. Under the modify tab, click parameters. You can define the parameter name, unit and expression. You can also define parameters using equations and existing parameter variables.
    <br><img width=600px height=auto class="center" src="../img/laserbox (1).PNG" ><br></p>
    <p>I will start with the base. Create a new component o organise the different parts. To use the parameters, simply type in the parameter name when defining the dimensions.
    <br><img width=600px height=auto class="center" src="../img/laserbox (7).PNG" ><br></p>
    <p>To make the base offset, I draw a center rectangle and define the offsets.
    <br><img width=600px height=auto class="center" src="../img/laserbox (8).PNG" ><br></p>
    <p>I then extrude with parameter &quot;thick&quot;
    <br><img width=600px height=auto class="center" src="../img/laserbox (9).PNG" ><br></p>
    <p>I next create a new sketch and draw a small rectangle touching the inner rectangle for the slot tabs.
    <br><img width=600px height=auto class="center" src="../img/laserbox (10).PNG" ><br></p>
    <p>I then extrude cut and used rectangular pattern to repeat the cut along the length.
    <br><img width=600px height=auto class="center" src="../img/laserbox (11).PNG" ><img width=600px height=auto class="center" src="../img/laserbox (12).PNG" ><br></p>
    <p>I create a new component for the back and create an offset plane such that it touches the surface of the tabs.
    <br><img width=600px height=auto class="center" src="../img/laserbox (13).PNG" ><br></p>
    <p>I draw a rectangle, dimension it with &quot;height&quot; and &quot;length&quot; and extrude it by &quot;thick&quot;
    <br><img width=600px height=auto class="center" src="../img/laserbox (14).PNG" ><img width=600px height=auto class="center" src="../img/laserbox (15).PNG" ><br></p>
    <p>I create a new sketch at the corner and draw a small rectangle of &quot;Htabwidth&quot; tall and &quot;Htabwidth&quot; above the bottom base.
    <br><img width=600px height=auto class="center" src="../img/laserbox (16).PNG" ><br></p>
    <p>Similar to the base tabs I cut extrude and use rectangular pattern to copy the cut along the height.
    <br><img width=600px height=auto class="center" src="../img/laserbox (17).PNG" ><img width=600px height=auto class="center" src="../img/laserbox (18).PNG" ><br></p>
    <p>To create the bottom tabs, I used the combine tool, selecting the back as the Target body and the base as the tool body. Selecting cut operation and keep tool.
    <br><img width=600px height=auto class="center" src="../img/laserbox (19).PNG" ><br></p>
    <p>Next I create a new component and extrude the back with offset such that it extrudes at the other side.
    <br><img width=600px height=auto class="center" src="../img/laserbox (21).PNG" ><br></p>
    <p>To cut the slots in the base I use combine tool, this time the front as the Tool body.
    <br><img width=600px height=auto class="center" src="../img/laserbox (22).PNG" ><br><br></p>

    <p>Now for the front, I create a new component and create new sketch on the surface of the back piece tabs. I then draw a rectangle and collinear constraint to the corners of the base, front and back.
      <br><img width=600px height=auto class="center" src="../img/laserbox (23).PNG" ><br><br></p>
      <p>Then I extrude inwards as a new body.
      <br><img width=600px height=auto class="center" src="../img/laserbox (24).PNG" ><br><br></p>
      <p>I forgot to cut the width tabs so I went back to the base component and repeat the tab cutting step: draw rectangle, dimension it, extrude cut and rectangular pattern.
      <br><img width=600px height=auto class="center" src="../img/laserbox (25).PNG" ><br><img width=600px height=auto class="center" src="../img/laserbox (26).PNG" ><br><img width=600px height=auto class="center" src="../img/laserbox (27).PNG" ><br><br></p>
      <p>Then to create tabs on the right piece I use combine tool cut, with the Right piece as the target body.
      <br><img width=600px height=auto class="center" src="../img/laserbox (30).PNG" ><br><br></p>
      <p>I create new component and extrude offset to the left side. Lastly I use combine cut to create the slot holes in the base.
      <br><img width=600px height=auto class="center" src="../img/laserbox (31).PNG" ><br><img width=600px height=auto class="center" src="../img/laserbox (32).PNG" ><br><br></p>
      <p>Pulling the pieces apart you can inspect the slots have been cut properly.
      <br><img width=600px height=auto class="center" src="../img/laserbox (34).PNG" ><br><br></p>
      <p>I then give it a wood texture for aesthetics.
      <br><img width=600px height=auto class="center" src="../img/laserbox (35).PNG" ><br><br></p>
      <p>Here is the completed box:
      <br><iframe src="https://ichat1316.autodesk360.com/shares/public/SH919a0QTf3c32634dcf80b74412ba71be75?mode=embed" width="640" height="480" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"  frameborder="0"></iframe><br></p>
      <a href="../Fusion 360/Laser cut box/laser cut box_.f3d" >download</a>

      <h4 id="-u-experimenting-with-parameters-br-u-"><u>Experimenting with parameters<br></u></h4>
      <p>With parameters you can basically make any box of different size without redrawing one everytime:</p>
      <p><strong>Base offset</strong></p>
      <div class="row">
        <div class="column">
          <figure>
            <img src="../img/0mm base.png" width=300px height=auto class="center">
            <figcaption><small>Base offset=0mm</small></figcaption>
          </figure>
        </div>
        <div class="column">
          <figure>
            <img src="../img/10mm base.png" width=300px height=auto class="center">
            <figcaption><small>Base offset=10mm</small></figcaption>
          </figure>
        </div>
      </div>
      <br>
      <p><strong>thickness</strong></p>
      <div class="row">
        <div class="column">
          <figure>
            <img src="../img/1mm thick.png" width=300px height=auto class="center">
            <figcaption><small>Thick = 1mm</small></figcaption>
          </figure>
        </div>
        <div class="column">
          <figure>
            <img src="../img/5mm thick.png" width=300px height=auto class="center">
            <figcaption><small>Thick = 5mm</small></figcaption>
          </figure>
        </div>
      </div>
      <br>
      <p><strong>Length</strong></p>
      <div class="row">
        <div class="column">
          <figure>
            <img src="../img/10mm length.png" width=300px height=auto class="center">
            <figcaption><small>Length = 10mm</small></figcaption>
          </figure>
        </div>
        <div class="column">
          <figure>
            <img src="../img/200mm length.png" width=300px height=auto class="center">
            <figcaption><small>Length = 200mm</small></figcaption>
          </figure>
        </div>
      </div>
      

  
</div>


</div>


            </div>

        </div>



        <div id="footer">
            Copyright &copy; Me (T_T), all rights reserved ~
        </div>

    </div>

    <button onclick="topFunction()" id="myBtn" title="Go to top">Back to Top</button>
    <script>
        mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}
    </script>


</body>



</html>